version: "3.0"
services:
  node:
    container_name: node
    hostname: node
    build: dockerfiles/node
    volumes:
      - ./home:/home/${USER}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    # user: ${UID}:${GID}
    working_dir: /home/${USER}
    tty: true
    ports:
      - 3000:3000
